### ISSUE TITLE
Create Alpha Pilot Prompt Document

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-documentation#21]
The shell for this document is in alpha-pilot-prompts.md
https://github.com/MyLife-Services/mylife-documentation/blob/base/alpha-team/alpha-pilot-prompts.md

Now here below is the long-form version of how we want to walk individuals through prompts. Let's start an alpha pilot prompt file as an asset - I'll make a ticket in the documentation repo and assign it to you.
Sequence of interactions to test basic bot functionality; note that auditor after each "issue" provide update, feedback, both positive and negative.

1. Collect Memory
   - select biographer bot (important!)
   - collect a memory with biog bot
   - check scrap book for memory
     - click refresh on memory bar if not seen
   - If not added, ask biographer bot in chat to save to MyLife
2. Direct Edit Memory
   - click on scrapbook
   - click on Memory bar
   - click on desired Memory
     - popup should appear
   - review popup memory summary
   - double-click or hit quill-and-paper icon
   - edit memory by hand
   - click disk icon to save
3. Interactive Edit Memory
   - [still using desired Memory above in #2]
   - click on rotating teal shadow text 
     - popup should close
     - memory should be active above chat
   - enter update or improvement to memory
   - refresh memory bar (important!)
   - test that content update occurred
4. Relive memory
   - click on scrapbook
   - click on Memory bar
   - click on desired Memory
     - popup should appear
   - click button relive memory 
     - popup should close
     - any active memories should close
   - Walkthrough Reliving Memory
     - once: update content during relive memory
     - otherwise: click Next to proceed
   - click 'x' to close out of reliving memory
   - refresh memory bar (important!)
   - Ensure relive content was incorporated
5. Delete a junk memory (create if needed)

**Comment by Vudum** [comment]
Here is the prompt document or test cases regarding these functionalities. If this reviewed and accepted, I can create a md file and push it documentation repo.

**Comment by Mookse** [comment]
@Vudum Yes - even if this contradicts something I said earlier, this thinking is better: Take the Google Sheet you created from this and convert that to Markdown with each test case being its own header-2 ##
this way we can feed it most easily to the alpha bot whose context intelligence aims to be assisting with the alpha project

**Comment by Vudum** [comment]
Created a pull request for this change here https://github.com/MyLife-Services/mylife-documentation/pull/27

**Comment by Vudum** [comment]
I believe this ticket can be closed now.
