### ISSUE TITLE
Demo video

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-documentation#24]
# MyLife Walkthrough Video
In addition to article, have a basic walkthrough of the current member product on video. Host it on YouTube. Build schedule for more versions with other interested volunteers.

- [x] [MyLife Initial Walkthrough](https://youtu.be/jMC5UDqs1Qk)

Steps to complete:

- [x] Zoom video recording of ewj demonstrating platform
- [x] Edit
- [x] Upload YouTube account

**Comment by Mookse** [comment]
https://youtu.be/jMC5UDqs1Qk
