### ISSUE TITLE
Alpha Project Test Cases

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-documentation#28]
# Alpha Project Test Cases

As we look to release the alpha, we need to develop a number of test cases related to release version 0.0.22. These test cases exist in their simplest form currently to collect, edit and relive a memory, but we will build out the cases to improve system comprehensive cover and elicit better feedback.

- [x] Register
  - [x] via Q
  - [x] for newsletter
- [x] Create Account
- [x] Login/Logout
  - [x] expect desktop saved?
- [x] Interface
  - [x] Bot Selection
  - [x] Bot Options
  - [x] Bot Naming
- [x] Avatar (bot)
  - [x] reset passphrase
  - [x] try tutorial
  - [x] what should public/private do?
- [x] Collect Memory (bot)
  - [x] try several different stories, one with a lot of names, one short, long, etc
  - [x] try another language?
- [x] Curate Memory (scrapbook + bot)
  - [x] Direct edit + save with icons
  - [x] Make memory ACTIVE
  - [x] change title (3 ways)
    - [x] Double Click on Scrapbook item name
    - [x] double-click on popup
    - [x] double-click on ACTIVE
    - [x] tell bot to change title while item is ACTIVE
  - [x] use "shadow" slider and add content
    - [x] try using shadow ideation (example: what would a normal person have done)
- [x] Relive Memory (scrapbook + bot)
  - [x] Version with changes, version without
  - [x] End Relive memory

**Comment by Vudum** [comment]
I have added more test cases here under sheet #28.
https://docs.google.com/spreadsheets/d/1PHF6q5Bh5LufrtutfYY46PeADGNo6WpLgIQbrdokqUQ/edit?gid=1378114951#gid=1378114951

**Comment by Mookse** [comment]
@Vudum I'm running with ticket #29 and I was planning to do my part in a markdown file - how were you thinking you would move these test cases over?

I've made a branch called `29-create-alpha-pilot...` for my test case if you want to use it as well; meanwhile, I'll include the gsheet link in the documentation

**Comment by Mookse** [comment]
Great work, @Vudum !
